//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateMustContent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> IsMust { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public Nullable<int> FormId { get; set; }
        public Nullable<int> MustContentType { get; set; }
        public Nullable<int> TemplatePhaseId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string Remark { get; set; }
    }
}
