//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatePhase
    {
        public int Id { get; set; }
        public int TemplateId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> MustContent { get; set; }
        //模板阶段是否有文档列表
        public int? HasDocList { get; set; }
        //模板阶段是否有关联表单
        public int? HasLinkedForm { get; set; }
        public int Sort { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string Remark { get; set; }
        public string DocListJson { get; set; }
        public string LinkedFormJson { get; set; }
    }
}
